Repository Unvanquished/Unvanquished, pull requests merged in 2020-04, with the labels that each got.

#1107 export game surfaceflags to CustomSurfaceFlags.h
  src/sgame/CustomSurfaceFlags.h
  src/sgame/sg_buildable.cpp
Labels: T-Cleanup

#1170 select alien class description independent of display order
  src/cgame/cg_rocket_dataformatter.cpp
  src/cgame/rocket/rocketCircleMenu.h
Labels: A-UI, T-Bug

#1167 macos: attempt to fix partial rendering issue on macOS Catalina, ref #1166
  macosx/Info.plist
Labels: A-Distribution, A-UI, OS-Mac, T-Bug
