Repository Unvanquished/Unvanquished, pull requests merged in 2022-09, with the labels that each got.

#2171 make slap velocity independent of mass
  src/sgame/sg_admin.cpp
Labels: A-Gamelogic, T-Enhancement

#2172 rmlui: Fix inconsistent coloring on names after Follow text.
  src/cgame/cg_rocket_draw.cpp
Labels: A-UI

#2189 Add error handling to the /give command
  src/sgame/sg_cmds.cpp
Labels: A-Gamelogic, A-Feedback, A-DevTools

#2161 cg_rocket_draw.cpp: cleanups
  src/cgame/cg_rocket_draw.cpp
Labels: T-Cleanup

#2174 rocket: prevent overflow
  src/cgame/rocket/rocket.cpp
Labels: A-UI, T-Bug

#2160 sgame: Remove a bunch of excess newlines
  src/sgame/sg_active.cpp
  src/sgame/sg_buildable.cpp
  src/sgame/sg_cm_world.cpp
  src/sgame/sg_combat.cpp
  src/sgame/sg_maprotation.cpp
  src/sgame/sg_momentum.cpp
  src/sgame/sg_spawn.cpp
  src/sgame/sg_spawn_mover.cpp
  src/sgame/sg_svcmds.cpp
Labels: A-UI, T-Cleanup, A-Logging
