Repository Unvanquished/Unvanquished, pull requests merged in 2023-05, with the labels that each got.

#2667 cg_main: fix navgen messages by copying translated string
  src/cgame/cg_main.cpp
Labels: A-UI, T-Bug

#2695 Don't grab cursor during loading if windowed
  src/cgame/cg_main.cpp
Labels: A-UI

#2701 translation: ignore breton for now, enable french
  pkg/unvanquished_src.dpkdir/.urcheon/action/build.txt
Labels: A-Translation

#2707 fix a warning about move being std::move
  src/sgame/sg_votes.cpp
Labels: A-Build

#2710 sg_cmds: silence clang warning for bitwise instead of logical operators
  src/sgame/sg_cmds.cpp
Labels: A-Build
