Repository Unvanquished/Unvanquished, pull requests merged in 2023-01, with the labels that each got.

#2353 On-demand background navmesh generation
  src/sgame/botlib/bot_load.cpp
  src/sgame/botlib/bot_nav.cpp
  src/sgame/botlib/bot_nav_edit.cpp
  src/sgame/sg_admin.cpp
  src/sgame/sg_bot.cpp
  src/sgame/sg_bot_local.h
  src/sgame/sg_bot_nav.cpp
  src/sgame/sg_bot_public.h
  src/sgame/sg_bot_util.h
  src/sgame/sg_main.cpp
Labels: A-Gamelogic, A-Server, A-Bots, T-Feature-Request

#2380 cgame: read map name from server config string instead of cvar, fix #2376
  src/cgame/cg_main.cpp
Labels: A-Client, T-Bug

#2374 cgame: better viewpos command
  src/cgame/cg_consolecmds.cpp
Labels: A-Client, T-Bug, T-Improvements
