Repository Unvanquished/Unvanquished, pull requests merged in 2024-10, with the labels that each got.

#2894 ui, presets: adjust for new cvars and cvar types
  pkg/unvanquished_src.dpkdir/presets/graphics/high.cfg
  pkg/unvanquished_src.dpkdir/presets/graphics/low.cfg
  pkg/unvanquished_src.dpkdir/presets/graphics/lowest.cfg
  pkg/unvanquished_src.dpkdir/presets/graphics/medium.cfg
  pkg/unvanquished_src.dpkdir/presets/graphics/ultra.cfg
  pkg/unvanquished_src.dpkdir/ui/options_graphics.rml
Labels: A-UI, T-Improvement

#3110 Update graphics settings
  pkg/unvanquished_src.dpkdir/ui/options_graphics.rml
Labels: A-UI, A-Client

#3127 Reduce reflection cubemap size options
  pkg/unvanquished_src.dpkdir/ui/options_graphics.rml
Labels: A-UI

#3141 Fix chargebar depth
  pkg/unvanquished_src.dpkdir/ui/hud_chargebar.rml
Labels: A-UI, T-Regression
